### ISSUE TITLE
help gan

### ISSUE THREAD

**Issue by ghost** [ahmadfawaid/Skripsweet#1]
gan ane nubie, pas ane jalanin composer install terminal nya malah ngeload 29 package termasuk symfoni, apakah langkah ini udah benar, 
terus apa bener jika saya masuk ke path des-master/application lalu jalanin terminal nya disini atau hanya di des-master aja, makasih gan mohon pencerahannya

**Comment by ahmadfawaid** [comment]
Iya mas udah bener.
Jalamin terminalnya di root folder mas.

**Comment by ghost** [comment]
@ahmadfawaid buat database nya gimana mas, saya tidak menemukan file sql di folder

**Comment by ahmadfawaid** [comment]
Buat database baru mas, terus sesuaikan nama database yg ada di folder .env dengan nama database yg baru dibuat

**Comment by ghost** [comment]
gan pas ane generate:key nya di root folder yang agan bilang, dapet error kaya gini https://pastebin.com/V9k9wcsS,
oh iya env.example file itu di edit ya apa dibuat file baru dengan format yang sama dan disesuai kan nama db nya?

**Comment by ahmadfawaid** [comment]
Ikuti tutorialnya mas, seharusnya sudah bisa

**Comment by ghost** [comment]
wah thankyou gan udah bisa jalan hehe, oh iya btw ini perhitungannya menggunakan metode double exponential ya ? soalnya ada parameter beta

**Comment by ahmadfawaid** [comment]
Itu kan udah ada di titlenya mas pakek metode apa

**Comment by ahmadfawaid** [comment]
@maverick66 iya mas sama", semoga bermanfaat
